### ISSUE TITLE
error to run the vlc container: Home directory not accessible: Permission denied

### ISSUE THREAD

**Issue by wjiang100** [galexrt/container-vlc#3]
docker run -d -v "$(pwd)":/data -p 8080:8080 quay.io/galexrt/vlc:latest file:///data/data/video/video1.mp4 --sout '#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}'

log: 

[000055e2f2effad0] main libvlc error: cannot open config file (/data/.config/vlc/vlcrc): Permission denied

Home directory not accessible: Permission denied

[000055e2f2f90190] vlcpulse audio output error: PulseAudio server connection failure: Connection refused

[000055e2f3082440] dbus interface error: Failed to connect to the D-Bus session daemon: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

[000055e2f3082440] main interface error: no suitable interface module

[000055e2f2effad0] main libvlc error: interface "dbus,none" initialization failed

[000055e2f3080a30] main interface error: no suitable interface module

[000055e2f2effad0] main libvlc error: interface "globalhotkeys,none" initialization failed

and this is where /data/.config/vlc:
vlc@eb1b2dc8edfa:~$ ls -l .config/    
total 72
drwx------ 21 1001 1002 4096 Jan 12 21:43 Code
drwx------  2 1001 1002 4096 Jan 13 05:29 Mousepad
-rw-r--r--  1 1001 1002   98 Jan 15 01:27 QtProject.conf
drwx------  2 1001 1002 4096 Nov 18 16:12 Thunar
drwx------  2 1001 1002 4096 Jan 14 20:43 autostart
drwx------  2 1001 1002 4096 Jan 15 01:27 dconf
drwx------ 33 1001 1002 4096 Jan 16 00:27 google-chrome
drwx------  2 1001 1002 4096 Nov 18 18:18 gtk-3.0
drwxr-xr-x  2 1001 1002 4096 Jan 12 21:55 jgit
-rw-r--r--  1 1001 1002  278 Jan 12 22:27 mimeapps.list
-rw-r--r--  1 1001 1002   89 Jan 14 16:11 pavucontrol.ini
drwx------  2 1001 1002 4096 Jan 14 18:43 procps
drwx------  2 1001 1002 4096 Nov 17 14:19 pulse
-rw-------  1 1001 1002  633 Nov 17 14:18 user-dirs.dirs
-rw-r--r--  1 1001 1002    5 Nov 17 14:18 user-dirs.locale
**drwx------  2 1001 1002 4096 Jan 14 21:05 vlc**
drwxr-xr-x  7 1001 1002 4096 Nov 18 16:04 xfce4
drwx------  2 1001 1002 4096 Nov 18 19:18 xfce4-session

**Comment by galexrt** [comment]
You probably need to run the container image with the same user and group as the files are owned.

Try the following command:

```
docker run -d -v "$(pwd)":/data -u $(id -u):$(id -g) -p 8080:8080 quay.io/galexrt/vlc:latest file:///data/data/video/video1.mp4 --sout '#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}'
```
If that doesn't work, add the flag `-e HOME=/data` before the image name

**Comment by wjiang100** [comment]
Thank you so much.  with Added -e HOME=/data. it works perfectly. 
docker run -d -v "$(pwd)":/data -u $(id -u):$(id -g) -p 8080:8080 -e HOME=/data quay.io/galexrt/vlc:latest file:///data/data/video/video1.mp4 --sout '#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}'

and the vlc stream could be viewed from the vlc on the host by http://127.0.0.1:8080.

**Comment by galexrt** [comment]
I have updated the reader file. Closing the issue.
